package(default_visibility = ["//visibility:public"])

# Compiler detection for conditional warning flags
config_setting(
    name = "clang_compiler",
    flag_values = {
        "@bazel_tools//tools/cpp:compiler": "clang",
    },
)

config_setting(
    name = "msvc_compiler",
    flag_values = {
        "@bazel_tools//tools/cpp:compiler": "msvc-cl",
    },
)

config_setting(
    name = "clang-cl_compiler",
    flag_values = {
        "@bazel_tools//tools/cpp:compiler": "clang-cl",
    },
)

# ASan suppression file for tests
filegroup(
    name = "asan_suppressions",
    srcs = [".asan_suppressions"],
)

# TSan suppression file for tests
filegroup(
    name = "tsan_suppressions",
    srcs = [".tsan_suppressions"],
)

# MSan suppression file for tests
filegroup(
    name = "msan_suppressions",
    srcs = [".msan_suppressions"],
)

# Exact headless-authority source/WGSL set. The generator also reads the
# checked-in allowlist and fails if this build declaration has drifted.
filegroup(
    name = "wreckwater_authority_content_inputs",
    srcs = [
        "//shaders:physics_attachments.wgsl",
        "//shaders:physics_ballistic.wgsl",
        "//shaders:physics_broad_phase.wgsl",
        "//shaders:physics_ccd.wgsl",
        "//shaders:physics_deterministic_primitives.wgsl",
        "//shaders:physics_dynamic_solver.wgsl",
        "//shaders:physics_event_readback.wgsl",
        "//shaders:physics_islands.wgsl",
        "//shaders:physics_narrow_phase.wgsl",
        "//shaders:physics_queries.wgsl",
        "//src/core:log.cpp",
        "//src/core:log.hpp",
        "//src/game:wreckwater_character_authority_bridge.cpp",
        "//src/game:wreckwater_character_authority_bridge.hpp",
        "//src/game:wreckwater_character_movement.cpp",
        "//src/game:wreckwater_character_movement.hpp",
        "//src/game:wreckwater_character_step.cpp",
        "//src/game:wreckwater_character_step.hpp",
        "//src/game:wreckwater_live_world.cpp",
        "//src/game:wreckwater_live_world.hpp",
        "//src/game:wreckwater_match.cpp",
        "//src/game:wreckwater_match.hpp",
        "//src/game:wreckwater_replay.cpp",
        "//src/game:wreckwater_replay.hpp",
        "//src/game:wreckwater_vessel_damage.cpp",
        "//src/game:wreckwater_vessel_damage.hpp",
        "//src/geometry:box_union.cpp",
        "//src/geometry:box_union.hpp",
        "//src/geometry:grid_types.hpp",
        "//src/geometry:orthogonal_geometry.hpp",
        "//src/gpu:context.cpp",
        "//src/gpu:context.hpp",
        "//src/gpu:resources.cpp",
        "//src/gpu:resources.hpp",
        "//src/gpu:shader_source.hpp",
        "//src/gpu:webgpu_compat.hpp",
        "//src/network:native_tcp_transport.cpp",
        "//src/network:native_tcp_transport.hpp",
        "//src/network:protocol.cpp",
        "//src/network:protocol.hpp",
        "//src/network:session_transport.hpp",
        "//src/network:wreckwater_protocol.cpp",
        "//src/network:wreckwater_protocol.hpp",
        "//src/physics:authored_body_frame.cpp",
        "//src/physics:authored_body_frame.hpp",
        "//src/physics:authored_shape.cpp",
        "//src/physics:authored_shape.hpp",
        "//src/physics:authored_shape_pool.cpp",
        "//src/physics:authored_shape_pool.hpp",
        "//src/physics:authored_shape_resources.hpp",
        "//src/physics:character/cpu_capsule_mover.cpp",
        "//src/physics:character/cpu_capsule_mover.hpp",
        "//src/physics:deterministic/lockstep_types.hpp",
        "//src/physics:deterministic/lockstep_world.hpp",
        "//src/physics:deterministic/replay.hpp",
        "//src/physics:gpu/debug_readback_ring.cpp",
        "//src/physics:gpu/debug_readback_ring.hpp",
        "//src/physics:gpu/deterministic_primitives.cpp",
        "//src/physics:gpu/deterministic_primitives.hpp",
        "//src/physics:gpu/gpu_attachments.cpp",
        "//src/physics:gpu/gpu_attachments.hpp",
        "//src/physics:gpu/gpu_authored_shapes.cpp",
        "//src/physics:gpu/gpu_authored_shapes.hpp",
        "//src/physics:gpu/gpu_body_metadata.hpp",
        "//src/physics:gpu/gpu_body_shape.hpp",
        "//src/physics:gpu/gpu_broad_phase.cpp",
        "//src/physics:gpu/gpu_broad_phase.hpp",
        "//src/physics:gpu/gpu_buffer_arena.cpp",
        "//src/physics:gpu/gpu_buffer_arena.hpp",
        "//src/physics:gpu/gpu_ccd.cpp",
        "//src/physics:gpu/gpu_ccd.hpp",
        "//src/physics:gpu/gpu_dynamic_solver.cpp",
        "//src/physics:gpu/gpu_dynamic_solver.hpp",
        "//src/physics:gpu/gpu_event_readback.cpp",
        "//src/physics:gpu/gpu_event_readback.hpp",
        "//src/physics:gpu/gpu_islands.cpp",
        "//src/physics:gpu/gpu_islands.hpp",
        "//src/physics:gpu/gpu_narrow_phase.cpp",
        "//src/physics:gpu/gpu_narrow_phase.hpp",
        "//src/physics:gpu/gpu_physics_backend.cpp",
        "//src/physics:gpu/gpu_physics_backend.hpp",
        "//src/physics:gpu/gpu_queries.cpp",
        "//src/physics:gpu/gpu_queries.hpp",
        "//src/physics:physics_backend.hpp",
        "//src/physics:physics_backend_factory.hpp",
        "//src/physics:physics_types.cpp",
        "//src/physics:physics_types.hpp",
        "//src/physics:physics_world.cpp",
        "//src/physics:physics_world.hpp",
        "//src/physics:rigid_mass_frame.cpp",
        "//src/physics:rigid_mass_frame.hpp",
        "//src/physics:shape_handle.hpp",
        "//src/physics:terrain_topology.hpp",
        "//src/physics:wreckwater_authority_backend_factory.cpp",
        "//src/server:wreckwater_authority_runtime.cpp",
        "//src/server:wreckwater_authority_runtime.hpp",
        "//src/server:wreckwater_server_main.cpp",
        "//src/terrain:lego_surface.hpp",
        "//src/terrain:mip_generator.cpp",
        "//src/terrain:mip_generator.hpp",
    ],
)

genrule(
    name = "wreckwater_build_content_header",
    srcs = [
        ":wreckwater_authority_content_inputs",
        "wreckwater_authority_content.allowlist",
    ],
    outs = ["generated/wreckwater_build_content.hpp"],
    cmd = "$(location //tools:generate_wreckwater_build_content) " +
          "--root \"$${PWD}\" " +
          "--allowlist $(location wreckwater_authority_content.allowlist) " +
          "--output $@ " +
          "--inputs $(locations :wreckwater_authority_content_inputs)",
    tools = ["//tools:generate_wreckwater_build_content"],
)

cc_library(
    name = "wreckwater_build_content",
    hdrs = [":wreckwater_build_content_header"],
    deps = ["//src/gpu:shader_source"],
)

cc_binary(
    name = "voxy_native",
    srcs = ["//src/engine/platform:native/entry.cpp", "//src/engine/platform:native/inspection_motion.hpp"],
    deps = [
        "//src/engine/platform:native_cove_saves",
        ":wreckwater_build_content",
        "//src:voxy_core",
        "//src/core:sha256",
        "//third_party:tinygltf",
    ],
    data = [
        "//data:cove_hud_font_notice",
        "//shaders:shaders",
        "//data:data",
        "voxy.cfg",
        "ridgebreak.cfg",
        "lego_shore.cfg",
        "lego_world.cfg",
        "salvage.cfg",
        "salvage_asset_fixture.cfg",
        "salvage_assembly_fixture.cfg",
        "salvage_hierarchy_fixture.cfg",
        "salvage_rotations_a.cfg",
        "salvage_rotations_b.cfg",
        "salvage_kit_narrow.cfg",
        "salvage_kit_broad.cfg",
        "salvage_kit_cargo.cfg",
        "salvage_material_fixture.cfg",
        "salvage_metric_fixture.cfg",
        "salvage_cove.cfg",
        "adventure.cfg",
        "//data:salvage_asset_fixture",
        "//data:salvage_hierarchy_probe",
        "//data:salvage_functional_kit",
        "//data:salvage_robot",
        "//data:adventure_runtime",
        "//data:salvage_environment",
        "//data:salvage_material_calibration",
        "//data:salvage_material_metric",
    ],
    defines = ["VOXY_NATIVE"],
)

cc_binary(
    name = "wreckwater_server",
    srcs = ["//src/server:wreckwater_server_main.cpp"],
    defines = ["VOXY_NATIVE"],
    deps = [
        ":wreckwater_build_content",
        "//src/server:wreckwater_headless_authority",
    ],
)

cc_binary(
    name = "ridgebreak_server",
    srcs = ["//src/server:ridgebreak_server_main.cpp"],
    defines = ["VOXY_NATIVE"],
    deps = [
        "//src/network:native_tcp_transport",
        "//src/server:ridgebreak_server_runtime",
    ],
)

cc_binary(
    name = "wreckwater_client_probe",
    srcs = ["//src/client:wreckwater_client_probe_main.cpp"],
    defines = ["VOXY_NATIVE"],
    deps = [
        ":wreckwater_build_content",
        "//src/client:wreckwater_client_probe",
        "//src/network:network",
    ],
)

load("@emsdk//emscripten_toolchain:wasm_rules.bzl", "wasm_cc_binary")

cc_binary(
    name = "voxy_wasm_cc",
    srcs = ["//src/engine/platform:wasm/entry.cpp"],
    deps = [
        "//src:voxy_core",
        "@emdawnwebgpu//:emdawnwebgpu",
    ],
    linkopts = [
        "-sWASM=1",
        # Web APIs reject views backed by resizable WebAssembly memory.
        "-sALLOW_MEMORY_GROWTH=0",
        "-sINITIAL_MEMORY=512MB",
        "-sSTACK_SIZE=1MB",
        "-sMODULARIZE=1",
        "-sEXPORT_NAME=VoxyModule",
        "-sEXPORTED_RUNTIME_METHODS=['ccall','cwrap','UTF8ToString','HEAPU8','callMain']",
        "-sEXPORTED_FUNCTIONS=['_main','_voxy_resize','_voxy_renderer_set_number','_voxy_renderer_get_number','_voxy_renderer_get_revision','_voxy_renderer_get_applied_revision','_voxy_mouse_move','_voxy_set_camera_pose','_voxy_key_event','_voxy_get_fps','_voxy_get_frame_count','_voxy_get_last_frame_cpu_ms','_voxy_get_last_frame_wall_ms','_voxy_get_gpu_frames_in_flight','_voxy_get_gpu_pacing_skips','_voxy_get_uncapped_fps','_voxy_set_uncapped_fps','_voxy_start_cube_pyramid_experiment','_voxy_start_browser_journey_benchmark','_voxy_get_browser_journey_benchmark_status','_voxy_get_browser_journey_benchmark_json','_voxy_start_render_throughput_benchmark','_voxy_get_render_throughput_status','_voxy_get_render_throughput_fps','_voxy_get_render_throughput_elapsed_ms','_voxy_get_render_throughput_completed_frames','_voxy_get_physics_substeps','_voxy_get_physics_resident_bodies','_voxy_set_throwable_body_limit','_voxy_get_physics_encoded_tick','_voxy_get_physics_stage_ms','_voxy_get_physics_stage_tick','_voxy_poll_physics_stage_timing','_voxy_get_polled_physics_stage_ms','_voxy_poll_render_stage_timing','_voxy_get_polled_render_stage_ms','_voxy_get_telemetry_json','_voxy_get_moto_hud_json','_voxy_is_initialized','_voxy_get_physics_backend','_voxy_start_physics_self_test','_voxy_get_physics_self_test_status','_voxy_get_physics_self_test_tick']",
        "-sASYNCIFY",
        "--js-library", "$(location @emdawnwebgpu//:src/library_webgpu_generated_struct_info.js)",
        "--js-library", "$(location @emdawnwebgpu//:src/library_webgpu_generated_sig_info.js)",
        "--js-library", "$(location @emdawnwebgpu//:src/library_webgpu_enum_tables.js)",
        "--js-library", "$(location @emdawnwebgpu//:src/library_webgpu.js)",
        "--preload-file", "shaders@/shaders",
        # Embed the data files used by the existing scene routes.
        "--preload-file", "data/generated/td_seed_1234_8192.ldh@/data/generated/td_seed_1234_8192.ldh",
        "--preload-file", "data/generated/td_seed_1234_2048_albedo.jpg@/data/generated/td_seed_1234_2048_albedo.jpg",
        "--preload-file", "data/generated/ocean_environment.png@/data/generated/ocean_environment.png",
        "--preload-file", "data/materials@/data/materials",
        "--preload-file", "data/moto/bike.vmesh@/data/moto/bike.vmesh",
        "--preload-file", "data/moto/rider.vmesh@/data/moto/rider.vmesh",
        "--preload-file", "data/moto/track.vmesh@/data/moto/track.vmesh",
        "--preload-file", "voxy.cfg@/voxy.cfg",
        "--preload-file", "ridgebreak.cfg@/ridgebreak.cfg",
        "--preload-file", "lego_shore.cfg@/lego_shore.cfg",
        "--preload-file", "lego_world.cfg@/lego_world.cfg",
        "--preload-file", "salvage.cfg@/salvage.cfg",
        "--preload-file", "salvage_asset_fixture.cfg@/salvage_asset_fixture.cfg",
        "--preload-file", "salvage_assembly_fixture.cfg@/salvage_assembly_fixture.cfg",
        "--preload-file", "salvage_hierarchy_fixture.cfg@/salvage_hierarchy_fixture.cfg",
        "--preload-file", "salvage_rotations_a.cfg@/salvage_rotations_a.cfg",
        "--preload-file", "salvage_rotations_b.cfg@/salvage_rotations_b.cfg",
        "--preload-file", "salvage_kit_narrow.cfg@/salvage_kit_narrow.cfg",
        "--preload-file", "data/salvage/fixture-kit-narrow.json@/data/salvage/fixture-kit-narrow.json",
        "--preload-file", "salvage_kit_broad.cfg@/salvage_kit_broad.cfg",
        "--preload-file", "data/salvage/fixture-kit-broad.json@/data/salvage/fixture-kit-broad.json",
        "--preload-file", "salvage_kit_cargo.cfg@/salvage_kit_cargo.cfg",
        "--preload-file", "salvage_material_fixture.cfg@/salvage_material_fixture.cfg",
        "--preload-file", "salvage_metric_fixture.cfg@/salvage_metric_fixture.cfg",
        "--preload-file", "adventure.cfg@/adventure.cfg",
        "--preload-file", "data/adventure/building-kit-r01/cooked@/data/adventure/building-kit-r01/cooked",
        "--preload-file", "salvage_cove.cfg@/salvage_cove.cfg",
        "--preload-file", "data/salvage/fixture-material-metric-r01.json@/data/salvage/fixture-material-metric-r01.json",
        "--preload-file", "data/salvage/fixture-material-shading-r02.json@/data/salvage/fixture-material-shading-r02.json",
        "--preload-file", "data/salvage/fixture-cove-r01.json@/data/salvage/fixture-cove-r01.json",
        "--preload-file", "data/salvage/material-calibration/r04/kit/winch/cooked@/data/salvage/material-calibration/r04/kit/winch/cooked",
        "--preload-file", "data/salvage/material-calibration/r04/kit/helm/cooked@/data/salvage/material-calibration/r04/kit/helm/cooked",
        "--preload-file", "data/salvage/material-calibration/r02/pontoon-r02/cooked@/data/salvage/material-calibration/r02/pontoon-r02/cooked",
        "--preload-file", "data/salvage/material-calibration/r02/kit/winch/cooked@/data/salvage/material-calibration/r02/kit/winch/cooked",
        "--preload-file", "data/salvage/material-calibration/r02/kit/helm/cooked@/data/salvage/material-calibration/r02/kit/helm/cooked",
        "--preload-file", "data/salvage/fixture-material-calibration-r01.json@/data/salvage/fixture-material-calibration-r01.json",
        "--preload-file", "data/salvage/material-calibration/r01/pontoon/cooked@/data/salvage/material-calibration/r01/pontoon/cooked",
        "--preload-file", "data/salvage/material-calibration/r01/kit/winch/cooked@/data/salvage/material-calibration/r01/kit/winch/cooked",
        "--preload-file", "data/salvage/fixture-kit-cargo.json@/data/salvage/fixture-kit-cargo.json",
        "--preload-file", "data/salvage/functional-kit/r09/beam/cooked@/data/salvage/functional-kit/r09/beam/cooked",
        "--preload-file", "data/salvage/functional-kit/r09/plate/cooked@/data/salvage/functional-kit/r09/plate/cooked",
        "--preload-file", "data/salvage/functional-kit/r09/engine/cooked@/data/salvage/functional-kit/r09/engine/cooked",
        "--preload-file", "data/salvage/functional-kit/r09/propeller/cooked@/data/salvage/functional-kit/r09/propeller/cooked",
        "--preload-file", "data/salvage/functional-kit/r09/helm/cooked@/data/salvage/functional-kit/r09/helm/cooked",
        "--preload-file", "data/salvage/functional-kit/r09/winch/cooked@/data/salvage/functional-kit/r09/winch/cooked",
        "--preload-file", "data/salvage/functional-kit/r09/cradle/cooked@/data/salvage/functional-kit/r09/cradle/cooked",
        "--preload-file", "data/salvage/functional-kit/r09/generator/cooked@/data/salvage/functional-kit/r09/generator/cooked",
        "--preload-file", "data/salvage/functional-kit/r09/crate/cooked@/data/salvage/functional-kit/r09/crate/cooked",
        "--preload-file", "data/salvage/fixture-pontoon-rotations-a.json@/data/salvage/fixture-pontoon-rotations-a.json",
        "--preload-file", "data/salvage/fixture-pontoon-rotations-b.json@/data/salvage/fixture-pontoon-rotations-b.json",
        "--preload-file", "data/salvage/fixture-hierarchy-v1.json@/data/salvage/fixture-hierarchy-v1.json",
        "--preload-file", "data/salvage/hierarchy_probe/candidates/v1-r02/cooked@/data/salvage/hierarchy_probe/candidates/v1-r02/cooked",
        "--preload-file", "data/salvage/fixture-pontoon-v2.json@/data/salvage/fixture-pontoon-v2.json",
        "--preload-file", "data/salvage/fixture-pontoon-assembly.json@/data/salvage/fixture-pontoon-assembly.json",
        "--preload-file", "data/salvage/pontoon/release-candidates/v2-rc01/cooked@/data/salvage/pontoon/release-candidates/v2-rc01/cooked",
        "--preload-file", "data/lego_shore.ldh@/data/lego_shore.ldh",
    ],
    additional_linker_inputs = [
        "@emdawnwebgpu//:js_files",
        "//shaders:shaders",
        "//data:data",
        "voxy.cfg",
        "ridgebreak.cfg",
        "lego_shore.cfg",
        "lego_world.cfg",
        "salvage.cfg",
        "salvage_asset_fixture.cfg",
        "salvage_assembly_fixture.cfg",
        "salvage_hierarchy_fixture.cfg",
        "salvage_rotations_a.cfg",
        "salvage_rotations_b.cfg",
        "salvage_kit_narrow.cfg",
        "salvage_kit_broad.cfg",
        "salvage_kit_cargo.cfg",
        "salvage_material_fixture.cfg",
        "salvage_metric_fixture.cfg",
        "salvage_cove.cfg",
        "adventure.cfg",
        "//data:salvage_asset_fixture",
        "//data:salvage_hierarchy_probe",
        "//data:salvage_functional_kit",
        "//data:salvage_robot",
        "//data:adventure_runtime",
        "//data:salvage_environment",
        "//data:salvage_material_calibration",
        "//data:salvage_material_metric",
    ],
    data = [
        "//shaders:shaders",
        "//data:data",
        "voxy.cfg",
        "ridgebreak.cfg",
        "lego_shore.cfg",
        "lego_world.cfg",
        "salvage.cfg",
        "salvage_asset_fixture.cfg",
        "salvage_assembly_fixture.cfg",
        "salvage_hierarchy_fixture.cfg",
        "salvage_rotations_a.cfg",
        "salvage_rotations_b.cfg",
        "salvage_kit_narrow.cfg",
        "salvage_kit_broad.cfg",
        "salvage_kit_cargo.cfg",
        "salvage_material_fixture.cfg",
        "salvage_metric_fixture.cfg",
        "salvage_cove.cfg",
        "adventure.cfg",
        "//data:salvage_asset_fixture",
        "//data:salvage_hierarchy_probe",
        "//data:salvage_functional_kit",
        "//data:salvage_robot",
        "//data:adventure_runtime",
        "//data:salvage_environment",
        "//data:salvage_material_calibration",
        "//data:salvage_material_metric",
        "@emdawnwebgpu//:src/library_webgpu.js",
        "@emdawnwebgpu//:src/library_webgpu_enum_tables.js",
        "@emdawnwebgpu//:src/library_webgpu_generated_struct_info.js",
        "@emdawnwebgpu//:src/library_webgpu_generated_sig_info.js",
    ],
    tags = ["no-sandbox"],
)

wasm_cc_binary(
    name = "voxy_wasm",
    cc_target = ":voxy_wasm_cc",
    tags = ["no-sandbox"],
)
