#!/usr/bin/env python3
"""Validate and package forest LODs; generate their shared render/collision bounds."""
import argparse, hashlib, json, math, struct, subprocess
from pathlib import Path

def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()

def main():
    p=argparse.ArgumentParser();p.add_argument('--package',type=Path,required=True)
    p.add_argument('--tool',type=Path,required=True);p.add_argument('--header',type=Path,required=True);a=p.parse_args()
    root=a.package.resolve();prov=json.loads((root/'provenance.json').read_text());reports=[]
    assert [entry['lod'] for entry in prov['lods']]==[0,1,2,3]
    for entry in prov['lods']:
        lod=entry['lod'];glb=root/'source'/f'forest-lod{lod}.glb';mesh=root/f'forest-lod{lod}.vmesh'
        assert sha(glb)==entry['glb_sha256']
        subprocess.run([str(a.tool.resolve()),'--profile','salvage-rigid-v1',str(glb),str(mesh)],check=True)
        raw=mesh.read_bytes();assert raw[:8]==b'VOXYMESH'
        header=struct.unpack_from('<14I13Q',raw,8);v,flags,nv,stride,ni,istride,ns,nm,nn,nmesh,nskin,nj,na,nac=header[:14]
        vo,io,so,mo,images,no,skins,anims,channels,channeldata,names,namesize,size=header[14:]
        assert v==1 and stride==72 and istride in (2,4) and nmesh==nn==6 and nm<=6 and ns<=24 and size==len(raw)
        assert not any((nskin,nj,na,nac)) and images==no
        points=[struct.unpack_from('<3f',raw,vo+i*stride) for i in range(nv)]
        for i,p in enumerate(points):
            assert all(math.isfinite(x) for x in p)
            normal=struct.unpack_from('<3f',raw,vo+i*stride+12)
            assert abs(sum(x*x for x in normal)-1)<.0003
        indices=struct.unpack_from('<'+('H' if istride==2 else 'I')*ni,raw,io)
        assert all(i<nv for i in indices)
        subs=[struct.unpack_from('<4I',raw,so+i*16) for i in range(ns)];triangles=[]
        for i,variant in enumerate(entry['variants']):
            node=struct.unpack_from('<10fiIiI',raw,no+i*64)
            assert node[:10]==(0.,0.,0.,0.,0.,0.,1.,1.,1.,1.) and node[10:13]==(-1,i,-1)
            start=names+node[13];assert raw[start:raw.index(0,start)].decode()==f'{i:02d}_'+variant['name']
            used=[indices[j] for begin,count,material,meshIndex in subs if meshIndex==i for j in range(begin//istride,begin//istride+count)]
            assert used
            lo=variant['bounds']['minimum'];hi=variant['bounds']['maximum']
            assert all(all(lo[k]-.001<=points[j][k]<=hi[k]+.001 for k in range(3)) for j in used)
            triangles.append(len(used)//3)
        assert max(triangles)<(18000,1500,700,180)[lod],triangles
        reports.append({'lod':lod,'bytes':len(raw),'sha256':sha(mesh),'triangles':triangles,'draws':ns,'vertices':nv})
    # Union bounds include the near foliage ornaments and every LOD silhouette.
    def vec(v):return '{'+','.join(f'{x:.6f}' for x in v)+'}'
    rows=[]
    for i in range(6):
        lo=[min(l['variants'][i]['bounds']['minimum'][k] for l in prov['lods'])-.01 for k in range(3)]
        hi=[max(l['variants'][i]['bounds']['maximum'][k] for l in prov['lods'])+.01 for k in range(3)]
        trunk=prov['lods'][0]['variants'][i]['trunk']
        rows.append('    {'+','.join(vec(x) for x in (lo,hi,trunk['minimum'],trunk['maximum']))+'}')
    a.header.write_text('// Generated by tools/adventure_assets/cook_forest.py; one unit per stud.\n#pragma once\n#include <array>\n#include <glm/vec3.hpp>\nnamespace voxy::game::adventure {\nstruct ForestGeometry {glm::dvec3 minimum, maximum, trunkMinimum, trunkMaximum;};\ninline constexpr std::array<ForestGeometry,6> forestGeometry{{\n'+',\n'.join(rows)+'\n}};\n}\n')
    (root/'manifest.json').write_text(json.dumps({'asset_id':prov['asset_id'],'lods':reports,'provenance_sha256':sha(root/'provenance.json'),'cooker_sha256':sha(a.tool.resolve()),'recipe_sha256':sha(Path(__file__)),'bounds_header_sha256':sha(a.header),'attribution':'source/ATTRIBUTION.md'},indent=2)+'\n')
    print(json.dumps(reports,indent=2))
if __name__=='__main__':main()
