#!/usr/bin/env python3
"""Generate the immutable C++ building catalog from installed canonical source."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'data/adventure/building-kit-r01/catalog.json'
ADDON_SOURCE = ROOT / 'data/adventure/door-r01/catalog.json'
LEGACY_SHA256 = 'fc9c763b22b5ef9d81e461608dea0f1b138d8f16a4940e9378442dc18a611150'
OUTPUT = ROOT / 'src/game/adventure/building_catalog.cpp'
ENUMS = ('Foundation', 'Floor', 'Wall', 'Doorway', 'Roof', 'Stair', 'Beam',
         'Brick1x2', 'Brick2x2', 'Brick2x4', 'Bed', 'Chest', 'Workbench', 'Pier')


def validated_catalog():
    assert hashlib.sha256(SOURCE.read_bytes()).hexdigest() == LEGACY_SHA256, 'IDs 1–14 remain immutable'
    doc = json.loads(SOURCE.read_text())
    assert doc['schema'] == 1 and doc['lattice_metres'] == .02
    assert len(doc['pieces']) == len(ENUMS)
    for index, piece in enumerate(doc['pieces']):
        assert piece['id'] == index + 1
        bounds = piece['bounds']
        assert bounds['minimum'][1] == 0 and 1 <= len(piece['solids']) <= 12
        for box in [bounds, *piece['solids']]:
            assert len(box['minimum']) == len(box['maximum']) == 3
            for axis in range(3):
                lo, hi = box['minimum'][axis], box['maximum'][axis]
                assert type(lo) is int and type(hi) is int and -1000 <= lo < hi <= 1000
                assert bounds['minimum'][axis] <= lo < hi <= bounds['maximum'][axis]
        assert piece['furniture'] in ('None', 'Bed', 'Chest', 'Workbench')
        assert type(piece['terrain_anchor']) is bool
        assert set(piece['cost']) == {'wood', 'stone', 'scrap'}
        assert all(type(n) is int and 0 <= n <= 999 for n in piece['cost'].values())
    return doc


def validated_door():
    doc = json.loads(ADDON_SOURCE.read_text())
    legacy = validated_catalog()
    assert doc['schema'] == 1 and doc['lattice_metres'] == .02
    assert doc['asset_id'] == 'voxys-adventure-hinged-door-r01'
    assert doc['legacy_catalog_sha256'] == LEGACY_SHA256 and doc['frame_piece_id'] == 4
    assert doc['hinge'] == [-32, 2, 0] and doc['open_yaw_degrees'] == -90
    assert doc['open_leaf'] == {'minimum': [-34, 2, 0], 'maximum': [-30, 110, 64]}
    piece = doc['piece']
    assert (piece['id'], piece['key'], piece['name']) == (15, 'hinged_door', 'Hinged door')
    assert piece['bounds'] == legacy['pieces'][3]['bounds']
    assert piece['solids'][:3] == legacy['pieces'][3]['solids'] and len(piece['solids']) == 4
    assert piece['solids'][3] == {'minimum': [-32, 2, -2], 'maximum': [32, 110, 2]}
    assert piece['cost'] == {'wood': 6, 'stone': 0, 'scrap': 2}
    assert piece['furniture'] == 'Door' and piece['terrain_anchor'] is False
    return doc


def catalog_fingerprint():
    return hashlib.sha256(b'voxys-adventure-building-catalog-v2\0'+SOURCE.read_bytes()+b'\0'+ADDON_SOURCE.read_bytes()).hexdigest()


def cpp_box(box):
    return '{{' + ','.join(map(str, box['minimum'])) + '},{' + ','.join(map(str, box['maximum'])) + '}}'


def generate():
    doc = validated_catalog()
    pieces = [*doc['pieces'], validated_door()['piece']]
    enums = (*ENUMS, 'HingedDoor')
    lines = ['// Generated by tools/adventure_assets/generate_catalog.py; legacy catalog + door add-on.',
             '#include "game/adventure/building_catalog.hpp"', '', '#include <array>', '',
             'namespace voxy::game::adventure {', 'namespace {']
    for index, piece in enumerate(pieces):
        lines.append(f'constexpr std::array<GridBox,{len(piece["solids"])}> solids{index + 1}{{{{')
        lines += ['    ' + cpp_box(box) + ',' for box in piece['solids']]
        lines.append('}};')
    lines.append('const std::array<BuildingDefinition,kBuildingPieceCount> definitions{{')
    for index, piece in enumerate(pieces):
        costs = ','.join(str(piece['cost'][k]) for k in ('wood', 'stone', 'scrap'))
        lines.append('    {PieceKind::' + enums[index] + ',"' + piece['key'] + '","' + piece['name'] + '",'
                     + cpp_box(piece['bounds']) + ',solids' + str(index + 1) + ',{' + costs + '},'
                     + 'FurnitureKind::' + piece['furniture'] + ',' + str(piece['terrain_anchor']).lower() + '},')
    lines += ['}};', '} // namespace', '',
              'std::span<const BuildingDefinition> buildingCatalog() noexcept { return definitions; }',
              'bool pieceKindValid(uint32_t value) noexcept { return value >= 1 && value <= kBuildingPieceCount; }',
              'const BuildingDefinition* buildingDefinition(PieceKind kind) noexcept {',
              '    const auto value=static_cast<uint32_t>(kind);',
              '    return pieceKindValid(value) ? &definitions[value-1] : nullptr;', '}',
              'std::string_view buildingCatalogFingerprint() noexcept {', f'    return "{catalog_fingerprint()}";', '}',
              'std::string_view legacyBuildingCatalogFingerprint() noexcept {', f'    return "{LEGACY_SHA256}";', '}',
              '} // namespace voxy::game::adventure', '']
    return '\n'.join(lines)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    generated = generate()
    if args.check:
        assert OUTPUT.read_text() == generated, 'compiled catalog differs; regenerate deliberately'
        print('Catalog source and compiled definitions agree.')
    else:
        OUTPUT.write_text(generated)
