// Generated by tools/adventure_assets/generate_catalog.py; edit catalog.json.
#include "game/adventure/building_catalog.hpp"

#include <array>

namespace voxy::game::adventure {
namespace {
constexpr std::array<GridBox,1> solids1{{
    {{-50,0,-50},{50,16,50}},
}};
constexpr std::array<GridBox,1> solids2{{
    {{-50,0,-50},{50,16,50}},
}};
constexpr std::array<GridBox,1> solids3{{
    {{-50,0,-8},{50,144,8}},
}};
constexpr std::array<GridBox,3> solids4{{
    {{-50,0,-8},{-34,112,8}},
    {{34,0,-8},{50,112,8}},
    {{-50,112,-8},{50,144,8}},
}};
constexpr std::array<GridBox,1> solids5{{
    {{-50,0,-50},{50,16,50}},
}};
constexpr std::array<GridBox,6> solids6{{
    {{-50,0,34},{50,8,50}},
    {{-50,0,17},{50,16,34}},
    {{-50,0,0},{50,24,17}},
    {{-50,0,-16},{50,32,0}},
    {{-50,0,-33},{50,40,-16}},
    {{-50,0,-50},{50,48,-33}},
}};
constexpr std::array<GridBox,1> solids7{{
    {{-50,0,-8},{50,16,8}},
}};
constexpr std::array<GridBox,1> solids8{{
    {{-50,0,-25},{50,48,25}},
}};
constexpr std::array<GridBox,1> solids9{{
    {{-50,0,-50},{50,48,50}},
}};
constexpr std::array<GridBox,1> solids10{{
    {{-100,0,-50},{100,48,50}},
}};
constexpr std::array<GridBox,6> solids11{{
    {{-25,0,-50},{-17,20,-42}},
    {{-25,0,42},{-17,20,50}},
    {{17,0,-50},{25,20,-42}},
    {{17,0,42},{25,20,50}},
    {{-25,20,-50},{25,32,50}},
    {{-25,32,-50},{25,40,-42}},
}};
constexpr std::array<GridBox,1> solids12{{
    {{-25,0,-25},{25,48,25}},
}};
constexpr std::array<GridBox,5> solids13{{
    {{-50,0,-25},{-42,36,-17}},
    {{-50,0,17},{-42,36,25}},
    {{42,0,-25},{50,36,-17}},
    {{42,0,17},{50,36,25}},
    {{-50,36,-25},{50,48,25}},
}};
constexpr std::array<GridBox,1> solids14{{
    {{-12,0,-12},{12,48,12}},
}};
const std::array<BuildingDefinition,kBuildingPieceCount> definitions{{
    {PieceKind::Foundation,"foundation","Foundation",{{-50,0,-50},{50,16,50}},solids1,{0,4,0},FurnitureKind::None,true},
    {PieceKind::Floor,"floor","Floor",{{-50,0,-50},{50,16,50}},solids2,{4,0,0},FurnitureKind::None,false},
    {PieceKind::Wall,"wall","Wall",{{-50,0,-8},{50,144,8}},solids3,{4,0,0},FurnitureKind::None,false},
    {PieceKind::Doorway,"doorway","Open doorway",{{-50,0,-8},{50,144,8}},solids4,{4,0,0},FurnitureKind::None,false},
    {PieceKind::Roof,"roof","Flat roof",{{-50,0,-50},{50,16,50}},solids5,{4,0,0},FurnitureKind::None,false},
    {PieceKind::Stair,"stair","Stairs",{{-50,0,-50},{50,48,50}},solids6,{4,2,0},FurnitureKind::None,false},
    {PieceKind::Beam,"beam","Beam",{{-50,0,-8},{50,16,8}},solids7,{2,0,0},FurnitureKind::None,false},
    {PieceKind::Brick1x2,"brick_1x2","Brick 1 × 2",{{-50,0,-25},{50,48,25}},solids8,{0,2,0},FurnitureKind::None,false},
    {PieceKind::Brick2x2,"brick_2x2","Brick 2 × 2",{{-50,0,-50},{50,48,50}},solids9,{0,4,0},FurnitureKind::None,false},
    {PieceKind::Brick2x4,"brick_2x4","Brick 2 × 4",{{-100,0,-50},{100,48,50}},solids10,{0,8,0},FurnitureKind::None,false},
    {PieceKind::Bed,"bed","Bed",{{-25,0,-50},{25,40,50}},solids11,{8,0,2},FurnitureKind::Bed,false},
    {PieceKind::Chest,"chest","Chest",{{-25,0,-25},{25,48,25}},solids12,{6,0,2},FurnitureKind::Chest,false},
    {PieceKind::Workbench,"workbench","Workbench",{{-50,0,-25},{50,48,25}},solids13,{8,0,4},FurnitureKind::Workbench,false},
    {PieceKind::Pier,"pier","Pier",{{-12,0,-12},{12,48,12}},solids14,{0,2,0},FurnitureKind::None,true},
}};
} // namespace

std::span<const BuildingDefinition> buildingCatalog() noexcept { return definitions; }
bool pieceKindValid(uint32_t value) noexcept { return value >= 1 && value <= kBuildingPieceCount; }
const BuildingDefinition* buildingDefinition(PieceKind kind) noexcept {
    const auto value=static_cast<uint32_t>(kind);
    return pieceKindValid(value) ? &definitions[value-1] : nullptr;
}
std::string_view buildingCatalogFingerprint() noexcept {
    return "fc9c763b22b5ef9d81e461608dea0f1b138d8f16a4940e9378442dc18a611150";
}
} // namespace voxy::game::adventure
