// Generated by tools/adventure_assets/generate_catalog.py; frozen legacy + door + versioned frontier modules.
#include "game/adventure/building_catalog.hpp"

#include <array>

namespace voxy::game::adventure {
namespace {
constexpr std::array<GridBox,1> solids1{{
    {{-50,0,-50},{50,16,50}},
}};
constexpr std::array<GridBox,1> solids2{{
    {{-50,0,-50},{50,16,50}},
}};
constexpr std::array<GridBox,1> solids3{{
    {{-50,0,-8},{50,144,8}},
}};
constexpr std::array<GridBox,3> solids4{{
    {{-50,0,-8},{-34,112,8}},
    {{34,0,-8},{50,112,8}},
    {{-50,112,-8},{50,144,8}},
}};
constexpr std::array<GridBox,1> solids5{{
    {{-50,0,-50},{50,16,50}},
}};
constexpr std::array<GridBox,6> solids6{{
    {{-50,0,34},{50,8,50}},
    {{-50,0,17},{50,16,34}},
    {{-50,0,0},{50,24,17}},
    {{-50,0,-16},{50,32,0}},
    {{-50,0,-33},{50,40,-16}},
    {{-50,0,-50},{50,48,-33}},
}};
constexpr std::array<GridBox,1> solids7{{
    {{-50,0,-8},{50,16,8}},
}};
constexpr std::array<GridBox,1> solids8{{
    {{-50,0,-25},{50,48,25}},
}};
constexpr std::array<GridBox,1> solids9{{
    {{-50,0,-50},{50,48,50}},
}};
constexpr std::array<GridBox,1> solids10{{
    {{-100,0,-50},{100,48,50}},
}};
constexpr std::array<GridBox,6> solids11{{
    {{-25,0,-50},{-17,20,-42}},
    {{-25,0,42},{-17,20,50}},
    {{17,0,-50},{25,20,-42}},
    {{17,0,42},{25,20,50}},
    {{-25,20,-50},{25,32,50}},
    {{-25,32,-50},{25,40,-42}},
}};
constexpr std::array<GridBox,1> solids12{{
    {{-25,0,-25},{25,48,25}},
}};
constexpr std::array<GridBox,5> solids13{{
    {{-50,0,-25},{-42,36,-17}},
    {{-50,0,17},{-42,36,25}},
    {{42,0,-25},{50,36,-17}},
    {{42,0,17},{50,36,25}},
    {{-50,36,-25},{50,48,25}},
}};
constexpr std::array<GridBox,1> solids14{{
    {{-12,0,-12},{12,48,12}},
}};
constexpr std::array<GridBox,4> solids15{{
    {{-50,0,-8},{-34,112,8}},
    {{34,0,-8},{50,112,8}},
    {{-50,112,-8},{50,144,8}},
    {{-32,2,-2},{32,110,2}},
}};
constexpr std::array<GridBox,1> solids16{{
    {{-150,0,-150},{150,16,150}},
}};
constexpr std::array<GridBox,1> solids17{{
    {{-150,0,-150},{150,16,150}},
}};
constexpr std::array<GridBox,1> solids18{{
    {{-150,0,-8},{150,288,8}},
}};
constexpr std::array<GridBox,3> solids19{{
    {{-150,0,-8},{-100,272,8}},
    {{100,0,-8},{150,272,8}},
    {{-150,272,-8},{150,288,8}},
}};
constexpr std::array<GridBox,1> solids20{{
    {{-150,0,-150},{150,16,150}},
}};
constexpr std::array<GridBox,54> solids21{{
    {{-150,0,134},{-50,8,150}},
    {{-150,0,117},{-50,16,134}},
    {{-150,0,100},{-50,24,117}},
    {{-150,0,84},{-50,32,100}},
    {{-150,0,67},{-50,40,84}},
    {{-150,0,50},{-50,48,67}},
    {{-50,0,134},{50,8,150}},
    {{-50,0,117},{50,16,134}},
    {{-50,0,100},{50,24,117}},
    {{-50,0,84},{50,32,100}},
    {{-50,0,67},{50,40,84}},
    {{-50,0,50},{50,48,67}},
    {{50,0,134},{150,8,150}},
    {{50,0,117},{150,16,134}},
    {{50,0,100},{150,24,117}},
    {{50,0,84},{150,32,100}},
    {{50,0,67},{150,40,84}},
    {{50,0,50},{150,48,67}},
    {{-150,48,34},{-50,56,50}},
    {{-150,48,17},{-50,64,34}},
    {{-150,48,0},{-50,72,17}},
    {{-150,48,-16},{-50,80,0}},
    {{-150,48,-33},{-50,88,-16}},
    {{-150,48,-50},{-50,96,-33}},
    {{-50,48,34},{50,56,50}},
    {{-50,48,17},{50,64,34}},
    {{-50,48,0},{50,72,17}},
    {{-50,48,-16},{50,80,0}},
    {{-50,48,-33},{50,88,-16}},
    {{-50,48,-50},{50,96,-33}},
    {{50,48,34},{150,56,50}},
    {{50,48,17},{150,64,34}},
    {{50,48,0},{150,72,17}},
    {{50,48,-16},{150,80,0}},
    {{50,48,-33},{150,88,-16}},
    {{50,48,-50},{150,96,-33}},
    {{-150,96,-66},{-50,104,-50}},
    {{-150,96,-83},{-50,112,-66}},
    {{-150,96,-100},{-50,120,-83}},
    {{-150,96,-116},{-50,128,-100}},
    {{-150,96,-133},{-50,136,-116}},
    {{-150,96,-150},{-50,144,-133}},
    {{-50,96,-66},{50,104,-50}},
    {{-50,96,-83},{50,112,-66}},
    {{-50,96,-100},{50,120,-83}},
    {{-50,96,-116},{50,128,-100}},
    {{-50,96,-133},{50,136,-116}},
    {{-50,96,-150},{50,144,-133}},
    {{50,96,-66},{150,104,-50}},
    {{50,96,-83},{150,112,-66}},
    {{50,96,-100},{150,120,-83}},
    {{50,96,-116},{150,128,-100}},
    {{50,96,-133},{150,136,-116}},
    {{50,96,-150},{150,144,-133}},
}};
constexpr std::array<GridBox,6> solids22{{
    {{-62,0,-125},{-42,50,-105}},
    {{-62,0,105},{-42,50,125}},
    {{42,0,-125},{62,50,-105}},
    {{42,0,105},{62,50,125}},
    {{-62,50,-125},{62,80,125}},
    {{-62,80,-125},{62,100,-105}},
}};
constexpr std::array<GridBox,1> solids23{{
    {{-62,0,-62},{62,120,62}},
}};
constexpr std::array<GridBox,5> solids24{{
    {{-125,0,-62},{-105,90,-42}},
    {{-125,0,42},{-105,90,62}},
    {{105,0,-62},{125,90,-42}},
    {{105,0,42},{125,90,62}},
    {{-125,90,-62},{125,120,62}},
}};
const std::array<BuildingDefinition,kBuildingPieceCount> definitions{{
    {PieceKind::Foundation,"foundation","Foundation",{{-50,0,-50},{50,16,50}},solids1,{0,4,0},FurnitureKind::None,true},
    {PieceKind::Floor,"floor","Floor",{{-50,0,-50},{50,16,50}},solids2,{4,0,0},FurnitureKind::None,false},
    {PieceKind::Wall,"wall","Wall",{{-50,0,-8},{50,144,8}},solids3,{4,0,0},FurnitureKind::None,false},
    {PieceKind::Doorway,"doorway","Open doorway",{{-50,0,-8},{50,144,8}},solids4,{4,0,0},FurnitureKind::None,false},
    {PieceKind::Roof,"roof","Flat roof",{{-50,0,-50},{50,16,50}},solids5,{4,0,0},FurnitureKind::None,false},
    {PieceKind::Stair,"stair","Stairs",{{-50,0,-50},{50,48,50}},solids6,{4,2,0},FurnitureKind::None,false},
    {PieceKind::Beam,"beam","Beam",{{-50,0,-8},{50,16,8}},solids7,{2,0,0},FurnitureKind::None,false},
    {PieceKind::Brick1x2,"brick_1x2","Brick 1 × 2",{{-50,0,-25},{50,48,25}},solids8,{0,2,0},FurnitureKind::None,false},
    {PieceKind::Brick2x2,"brick_2x2","Brick 2 × 2",{{-50,0,-50},{50,48,50}},solids9,{0,4,0},FurnitureKind::None,false},
    {PieceKind::Brick2x4,"brick_2x4","Brick 2 × 4",{{-100,0,-50},{100,48,50}},solids10,{0,8,0},FurnitureKind::None,false},
    {PieceKind::Bed,"bed","Bed",{{-25,0,-50},{25,40,50}},solids11,{8,0,2},FurnitureKind::Bed,false},
    {PieceKind::Chest,"chest","Chest",{{-25,0,-25},{25,48,25}},solids12,{6,0,2},FurnitureKind::Chest,false},
    {PieceKind::Workbench,"workbench","Workbench",{{-50,0,-25},{50,48,25}},solids13,{8,0,4},FurnitureKind::Workbench,false},
    {PieceKind::Pier,"pier","Pier",{{-12,0,-12},{12,48,12}},solids14,{0,2,0},FurnitureKind::None,true},
    {PieceKind::HingedDoor,"hinged_door","Hinged door",{{-50,0,-8},{50,144,8}},solids15,{6,0,2},FurnitureKind::Door,false},
    {PieceKind::FrontierFoundation,"frontier_foundation","Stone foundation",{{-150,0,-150},{150,16,150}},solids16,{0,8,0},FurnitureKind::None,true},
    {PieceKind::FrontierDeck,"frontier_deck","Bridge deck",{{-150,0,-150},{150,16,150}},solids17,{8,0,0},FurnitureKind::None,false},
    {PieceKind::FrontierWall,"frontier_wall","Shelter wall",{{-150,0,-8},{150,288,8}},solids18,{10,0,0},FurnitureKind::None,false},
    {PieceKind::FrontierDoorway,"frontier_doorway","Wide doorway",{{-150,0,-8},{150,288,8}},solids19,{8,0,0},FurnitureKind::None,false},
    {PieceKind::FrontierRoof,"frontier_roof","Shelter roof",{{-150,0,-150},{150,16,150}},solids20,{8,0,0},FurnitureKind::None,false},
    {PieceKind::FrontierStairs,"frontier_stairs","Trail stairs",{{-150,0,-150},{150,144,150}},solids21,{8,4,0},FurnitureKind::None,false},
    {PieceKind::FrontierBed,"frontier_bed","Camp bed",{{-62,0,-125},{62,100,125}},solids22,{8,0,2},FurnitureKind::Bed,false},
    {PieceKind::FrontierChest,"frontier_chest","Supply chest",{{-62,0,-62},{62,120,62}},solids23,{6,0,2},FurnitureKind::Chest,false},
    {PieceKind::FrontierWorkbench,"frontier_workbench","Field workbench",{{-125,0,-62},{125,120,62}},solids24,{8,0,4},FurnitureKind::Workbench,false},
}};
const std::array<BuildingVisual,1> visuals1{{
    {PieceKind::Foundation,{0,0,0},{1,1,1}},
}};
const std::array<BuildingVisual,1> visuals2{{
    {PieceKind::Floor,{0,0,0},{1,1,1}},
}};
const std::array<BuildingVisual,1> visuals3{{
    {PieceKind::Wall,{0,0,0},{1,1,1}},
}};
const std::array<BuildingVisual,1> visuals4{{
    {PieceKind::Doorway,{0,0,0},{1,1,1}},
}};
const std::array<BuildingVisual,1> visuals5{{
    {PieceKind::Roof,{0,0,0},{1,1,1}},
}};
const std::array<BuildingVisual,1> visuals6{{
    {PieceKind::Stair,{0,0,0},{1,1,1}},
}};
const std::array<BuildingVisual,1> visuals7{{
    {PieceKind::Beam,{0,0,0},{1,1,1}},
}};
const std::array<BuildingVisual,1> visuals8{{
    {PieceKind::Brick1x2,{0,0,0},{1,1,1}},
}};
const std::array<BuildingVisual,1> visuals9{{
    {PieceKind::Brick2x2,{0,0,0},{1,1,1}},
}};
const std::array<BuildingVisual,1> visuals10{{
    {PieceKind::Brick2x4,{0,0,0},{1,1,1}},
}};
const std::array<BuildingVisual,1> visuals11{{
    {PieceKind::Bed,{0,0,0},{1,1,1}},
}};
const std::array<BuildingVisual,1> visuals12{{
    {PieceKind::Chest,{0,0,0},{1,1,1}},
}};
const std::array<BuildingVisual,1> visuals13{{
    {PieceKind::Workbench,{0,0,0},{1,1,1}},
}};
const std::array<BuildingVisual,1> visuals14{{
    {PieceKind::Pier,{0,0,0},{1,1,1}},
}};
const std::array<BuildingVisual,1> visuals15{{
    {PieceKind::Doorway,{0,0,0},{1,1,1}},
}};
const std::array<BuildingVisual,9> visuals16{{
    {PieceKind::Foundation,{-2,0,-2},{1,1,1}},
    {PieceKind::Foundation,{-2,0,0},{1,1,1}},
    {PieceKind::Foundation,{-2,0,2},{1,1,1}},
    {PieceKind::Foundation,{0,0,-2},{1,1,1}},
    {PieceKind::Foundation,{0,0,0},{1,1,1}},
    {PieceKind::Foundation,{0,0,2},{1,1,1}},
    {PieceKind::Foundation,{2,0,-2},{1,1,1}},
    {PieceKind::Foundation,{2,0,0},{1,1,1}},
    {PieceKind::Foundation,{2,0,2},{1,1,1}},
}};
const std::array<BuildingVisual,9> visuals17{{
    {PieceKind::Floor,{-2,0,-2},{1,1,1}},
    {PieceKind::Floor,{-2,0,0},{1,1,1}},
    {PieceKind::Floor,{-2,0,2},{1,1,1}},
    {PieceKind::Floor,{0,0,-2},{1,1,1}},
    {PieceKind::Floor,{0,0,0},{1,1,1}},
    {PieceKind::Floor,{0,0,2},{1,1,1}},
    {PieceKind::Floor,{2,0,-2},{1,1,1}},
    {PieceKind::Floor,{2,0,0},{1,1,1}},
    {PieceKind::Floor,{2,0,2},{1,1,1}},
}};
const std::array<BuildingVisual,6> visuals18{{
    {PieceKind::Wall,{-2,0,0},{1,1,1}},
    {PieceKind::Wall,{-2,2.8799999999999999,0},{1,1,1}},
    {PieceKind::Wall,{0,0,0},{1,1,1}},
    {PieceKind::Wall,{0,2.8799999999999999,0},{1,1,1}},
    {PieceKind::Wall,{2,0,0},{1,1,1}},
    {PieceKind::Wall,{2,2.8799999999999999,0},{1,1,1}},
}};
const std::array<BuildingVisual,7> visuals19{{
    {PieceKind::Wall,{-2.5,0,0},{0.5,1,1}},
    {PieceKind::Wall,{2.5,0,0},{0.5,1,1}},
    {PieceKind::Wall,{-2.5,2.8799999999999999,0},{0.5,0.88888888888888884,1}},
    {PieceKind::Wall,{2.5,2.8799999999999999,0},{0.5,0.88888888888888884,1}},
    {PieceKind::Beam,{-2,5.4400000000000004,0},{1,1,1}},
    {PieceKind::Beam,{0,5.4400000000000004,0},{1,1,1}},
    {PieceKind::Beam,{2,5.4400000000000004,0},{1,1,1}},
}};
const std::array<BuildingVisual,9> visuals20{{
    {PieceKind::Roof,{-2,0,-2},{1,1,1}},
    {PieceKind::Roof,{-2,0,0},{1,1,1}},
    {PieceKind::Roof,{-2,0,2},{1,1,1}},
    {PieceKind::Roof,{0,0,-2},{1,1,1}},
    {PieceKind::Roof,{0,0,0},{1,1,1}},
    {PieceKind::Roof,{0,0,2},{1,1,1}},
    {PieceKind::Roof,{2,0,-2},{1,1,1}},
    {PieceKind::Roof,{2,0,0},{1,1,1}},
    {PieceKind::Roof,{2,0,2},{1,1,1}},
}};
const std::array<BuildingVisual,9> visuals21{{
    {PieceKind::Stair,{-2,0,2},{1,1,1}},
    {PieceKind::Stair,{0,0,2},{1,1,1}},
    {PieceKind::Stair,{2,0,2},{1,1,1}},
    {PieceKind::Stair,{-2,0.95999999999999996,0},{1,1,1}},
    {PieceKind::Stair,{0,0.95999999999999996,0},{1,1,1}},
    {PieceKind::Stair,{2,0.95999999999999996,0},{1,1,1}},
    {PieceKind::Stair,{-2,1.9199999999999999,-2},{1,1,1}},
    {PieceKind::Stair,{0,1.9199999999999999,-2},{1,1,1}},
    {PieceKind::Stair,{2,1.9199999999999999,-2},{1,1,1}},
}};
const std::array<BuildingVisual,1> visuals22{{
    {PieceKind::Bed,{0,0,0},{2.5,2.5,2.5}},
}};
const std::array<BuildingVisual,1> visuals23{{
    {PieceKind::Chest,{0,0,0},{2.5,2.5,2.5}},
}};
const std::array<BuildingVisual,1> visuals24{{
    {PieceKind::Workbench,{0,0,0},{2.5,2.5,2.5}},
}};
const std::array<std::span<const BuildingVisual>,kBuildingPieceCount> visuals{{
    visuals1,visuals2,visuals3,visuals4,visuals5,visuals6,visuals7,visuals8,visuals9,visuals10,visuals11,visuals12,visuals13,visuals14,visuals15,visuals16,visuals17,visuals18,visuals19,visuals20,visuals21,visuals22,visuals23,visuals24
}};
constexpr std::array<PieceKind,kBuildingPieceCount> icons{{
    PieceKind::Foundation,PieceKind::Floor,PieceKind::Wall,PieceKind::Doorway,PieceKind::Roof,PieceKind::Stair,PieceKind::Beam,PieceKind::Brick1x2,PieceKind::Brick2x2,PieceKind::Brick2x4,PieceKind::Bed,PieceKind::Chest,PieceKind::Workbench,PieceKind::Pier,PieceKind::Doorway,PieceKind::Foundation,PieceKind::Floor,PieceKind::Wall,PieceKind::Doorway,PieceKind::Roof,PieceKind::Stair,PieceKind::Bed,PieceKind::Chest,PieceKind::Workbench
}};
} // namespace

std::span<const BuildingDefinition> buildingCatalog() noexcept { return definitions; }
bool pieceKindValid(uint32_t value) noexcept { return value >= 1 && value <= kBuildingPieceCount; }
const BuildingDefinition* buildingDefinition(PieceKind kind) noexcept {
    const auto value=static_cast<uint32_t>(kind);
    return pieceKindValid(value) ? &definitions[value-1] : nullptr;
}
std::span<const BuildingVisual> buildingVisuals(PieceKind kind) noexcept {
    const auto value=static_cast<uint32_t>(kind);
    return pieceKindValid(value) ? visuals[value-1] : std::span<const BuildingVisual>{};
}
PieceKind buildingIconKind(PieceKind kind) noexcept {
    const auto value=static_cast<uint32_t>(kind);
    return pieceKindValid(value) ? icons[value-1] : PieceKind::Foundation;
}
bool isFrontierPiece(PieceKind kind) noexcept {
    const auto value=static_cast<uint32_t>(kind);
    return value>kLegacyBuildingPieceCount && value<=kBuildingPieceCount;
}
std::string_view frontierBuildingCatalogFingerprint() noexcept {
    return "58fc91a88b50225bd1bb5be447c10747c5332447c10e2860fd72c8a07f106a9f";
}
std::string_view buildingCatalogFingerprint() noexcept {
    return "9059ecdef3c9530d419fdcffbe74ca0501472f73a83f8f901147f52122a50a98";
}
std::string_view legacyBuildingCatalogFingerprint() noexcept {
    return "fc9c763b22b5ef9d81e461608dea0f1b138d8f16a4940e9378442dc18a611150";
}
} // namespace voxy::game::adventure
