package(default_visibility = ["//visibility:public"])

filegroup(
    name = "data",
    srcs = [
        "canyon_4k.ldh",
        "canyon_diffuse.jpg",
        "generated/td_seed_1234_2048.ldh",
        "generated/td_seed_1234_2048_relief.png",
    ],
)
