package(default_visibility = ["//visibility:public"])

filegroup(
    name = "data",
    srcs = [
        "generated/td_seed_1234_8192_albedo.jpg",
        "generated/td_seed_1234_8192.ldh",
    ],
)
