package(default_visibility = ["//visibility:public"])

filegroup(
    name = "data",
    srcs = [
        "moto/bike.glb",
        "moto/bike.vmesh",
        "moto/rider.glb",
        "moto/rider.vmesh",
        "moto/track.glb",
        "moto/track.vmesh",
        "generated/ocean_environment.png",
        "generated/td_seed_1234_2048_albedo.jpg",
        "generated/td_seed_1234_8192.ldh",
        "lego_shore.ldh",
        "materials/Grass001_1K-JPG_Color.jpg",
        "materials/Grass001_1K-JPG_NormalGL.jpg",
        "materials/Grass001_1K-JPG_Roughness.jpg",
        "materials/Ground037_1K-JPG_Color.jpg",
        "materials/Ground037_1K-JPG_NormalGL.jpg",
        "materials/Ground037_1K-JPG_Roughness.jpg",
        "materials/Ground054_1K-JPG_Color.jpg",
        "materials/Ground054_1K-JPG_NormalGL.jpg",
        "materials/Ground054_1K-JPG_Roughness.jpg",
        "materials/Rock050_1K-JPG_Color.jpg",
        "materials/Rock050_1K-JPG_NormalGL.jpg",
        "materials/Rock050_1K-JPG_Roughness.jpg",
    ],
)

filegroup(
    name = "performance_golden",
    srcs = ["canyon_8k.ldh"],
)
