#!/usr/bin/env python3
"""Package an optional WASM data pack that only some experiences download.

Emscripten's file packager writes the pack's .data file and the JavaScript
that mounts it into the virtual filesystem. That script is linked into
voxy_wasm.js with --pre-js, but only runs when the page lists the pack in
Module.voxyDataPacks, so experiences that never read these files neither
download them nor delay startup for them.
"""

import argparse
from pathlib import Path
import re
import subprocess
import sys
import tempfile


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--packager", type=Path, required=True,
                        help="Emscripten tools/file_packager.py")
    parser.add_argument("--name", required=True)
    parser.add_argument("--data", type=Path, required=True,
                        help="Output .data file served next to voxy_wasm.js")
    parser.add_argument("--pre-js", type=Path, required=True)
    parser.add_argument("files", nargs="+", help="source@/virtual/path entries")
    args = parser.parse_args()
    if not re.fullmatch(r"[a-z][a-z0-9-]*", args.name):
        parser.error("Pack names are lowercase identifiers")

    with tempfile.TemporaryDirectory() as tmp:
        js = Path(tmp) / "pack.js"
        # --from-emcc: the code is embedded in the module factory, which
        # already defines Module and the filesystem helpers it calls.
        subprocess.run([sys.executable, str(args.packager), str(args.data),
                        "--from-emcc", "--preload", *args.files,
                        f"--js-output={js}"], check=True)
        body = js.read_text()

    args.pre_js.write_text(
        f"// Optional data pack '{args.name}', generated by {Path(__file__).name}.\n"
        f"if (Module['voxyDataPacks'] && Module['voxyDataPacks'].indexOf('{args.name}') >= 0) {{\n"
        f"{body}\n}}\n")


if __name__ == "__main__":
    main()
