#!/usr/bin/env python3
"""Rebuild the bounded native HUD's DejaVu Sans coverage atlas. No runtime font dependency."""
import argparse
import hashlib
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont, __version__ as pillow_version

ROOT = Path(__file__).resolve().parents[1]
FONT = ROOT / "data/fonts/cove-hud/DejaVuSans.ttf"
OUTPUT = ROOT / "src/render/cove_hud_font.inc"


def generate():
    font = ImageFont.truetype(str(FONT), 32)
    atlas = Image.new("L", (512, 256))
    draw = ImageDraw.Draw(atlas)
    # Four white texels for solid panels, with a transparent surrounding gutter.
    draw.rectangle((1, 1, 2, 2), fill=255)
    x, y, row = 6, 2, 0
    glyphs = []
    for code in range(32, 127):
        char = chr(code)
        left, top, right, bottom = font.getbbox(char)
        width, height = right - left, bottom - top
        if x + width + 2 > 512:
            x, y, row = 2, y + row + 4, 0
        if y + height + 2 > 256:
            raise RuntimeError("HUD glyph atlas exceeds its fixed budget")
        draw.text((x-left, y-top), char, font=font, fill=255)
        glyphs.append((x, y, width, height, left, top, round(font.getlength(char)*64)))
        x += width + 4
        row = max(row, height)
    raw = atlas.tobytes()
    encoded = []
    for value in raw:
        if encoded and encoded[-1] == value and encoded[-2] < 255:
            encoded[-2] += 1
        else:
            encoded.extend((1, value))
    lines = ["// Generated by tools/make_cove_hud_font.py; do not edit.",
             "// DejaVu Sans: Bitstream Vera license; see data/fonts/cove-hud/README.md.",
             f"// Font SHA256: {hashlib.sha256(FONT.read_bytes()).hexdigest()}",
             f"// Atlas SHA256: {hashlib.sha256(raw).hexdigest()}; Pillow {pillow_version}.",
             "struct HudGlyph { uint16_t x,y,width,height; int16_t left,top; uint16_t advance64; };",
             "constexpr std::array<HudGlyph,95> hudGlyphs{{"]
    lines += ["    {" + ",".join(map(str, g)) + "}," for g in glyphs]
    lines += ["}};", "constexpr uint8_t hudAtlasRle[]{"]
    lines += ["    " + ",".join(map(str, encoded[i:i+32])) + "," for i in range(0,len(encoded),32)]
    lines += ["};", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = generate()
    if args.check:
        if OUTPUT.read_text() != output:
            raise SystemExit("HUD font atlas differs; regenerate with the recorded Pillow version")
        print("HUD font atlas and glyph metrics match the licensed source")
    else:
        OUTPUT.write_text(output)
